root: true
env:
  commonjs: true
  es2021: true
  node: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2021
rules:
  no-underscore-dangle: off
  no-console: off
  comma-dangle: off
  no-useless-catch: off
  id-length: [error, {exceptions: ["x","y","_","$", "e"]}]
  object-shorthand: off
  prefer-destructuring: off
  max-len: [2, 200, {ignoreStrings: true , ignoreComments: true}]

  # temp exclusions - fix & re-enable rules when possible
  class-methods-use-this: off
  no-param-reassign: off
  no-restricted-syntax: off
